### ISSUE TITLE
undefined method `eager_load_paths` on Rails 4.2

### ISSUE THREAD

**Issue by masterkain** [spree/deface#139]
upgraded a Spree from 2.4 to 3.0 and Rails to 4.2 and I'm getting this on app startup:

```
/Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `eager_load_paths' for #<Rails::Railtie::Configuration:0x007fbc602a8c70> (NoMethodError)
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:50:in `block (2 levels) in <class:Railtie>'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:48:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:48:in `block in <class:Railtie>'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/kain/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/kain/.rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
```

**Comment by masterkain** [comment]
mm, the problem seems to be related to `dotenv-rails` in my Gemfile, although it doesn't appear in the stack trace.

**Comment by cbrunsdon** [comment]
Aye, @masterkain, it looks like dotenv's railties defines ```root``` here:
https://github.com/bkeepers/dotenv/blob/master/lib/dotenv/rails.rb#L37

Which conflicts with assumptions deface is making here:
https://github.com/spree/deface/blob/master/lib/deface/railtie.rb#L49

I am tempted to add another check to see if the config defines eager load paths.
