### ISSUE TITLE
HAML 5 broken

### ISSUE THREAD

**Issue by zubietaroberto** [spree/deface#172]
Deface works until HAML 5 beta 2. If you update to HAML 5 then Deface will break all the attributes. This is what happens:

I have this layout file (summarized):
```HAML
!!!
/[if IE 7] <html class="no-js ie7 oldie" lang="es">
/[if IE 8] <html class="no-js ie8 oldie" lang="es">
/[if gt IE 9]><!
%html{lang: I18n.locale}
  /<![endif]

-# Omitted for brevity
```
When I use Haml 5 with this file then rails throws at me this error:

```
ArgumentError in Spree::HomeController#index
Old attributes must start with "{" and end with "}"

haml (5.0.1) lib/haml/parser.rb:213:in `old='
  def old=(value)
        unless value =~ /\A{.*}\z/m
          raise ArgumentError.new('Old attributes must start with "{" and end with "}"')
        end
        super
      end

deface (1.2.0) lib/deface/haml_converter.rb:94:in `initialize'
        options[:compiler_class] = Compiler
        options[:parser_class]   = Parser
        super(template, options)
      end
    else
```

When I use the stack trace to debug `value` in the HAML Parser class  it returns `"\"data-erb-lang\" => \"<%= I18n.locale %>\""`. This is wrong.

However, if I write the attributtes in the HTML element in the old ruby rocket style, like this: 
```HAML
%html{:lang => I18n.locale}
```

It outputs this:

```HTML
<html>
</html>
```
It silently fails to parse the attributes.

**Comment by jormon** [comment]
🏏 s

**Comment by meowsus** [comment]
I am having a similar issue, almost a year and a half later it looks like.

If I have a partial located at `app/views/shared/_fields.html.haml` that contains:

```haml
.foobar
%div{ data: { foo_bar: '' } }
```
And an override at `app/overrides/my_fields.rb` that contains:

```ruby
Deface::Override.new(                                                           
  virtual_path: 'shared/_fields',                   
  name: 'my_fields',                                   
  insert_top: '.foobar',
  partial: 'shared/my_fields'
)
```

And the new partial at `app/shared/_my_fields.html.haml that contains: 

```haml
%div{ data: { baz: '' } }
```

The expected output should be:

```html
<div class='foobar'>
   <div data-baz=''></div>
</div>
<div data-foo-bar=''></div>
```

But it is actually:

```html
<div class='foobar'>
   <div data-baz=''></div>
</div>
<div></div>
```

Whatever data attributes I have already defined in the partial I want to deface are stripped, but the partial I'm inserting remains unmolested.

For what it's worth this seems to be happening before the insertion is happening. If I run `bin/rails deface:get_result[shared/_fields]` the BEFORE section contains no reference to `data-foo-bar`.

Here are the versions of as many gems as I can think of that might be related to the problem:

* nokogiri 1.10.3
* rails 5.2.3
* deface 1.3.2
* haml 5.0.4

Please let me know if I can help in any way to figure this out, as it's a total showstopper from me being able to use this in my project :|

Thanks in advance for your time!

**Comment by meowsus** [comment]
So I had some time before my day finished so I spurred up a demo to help in debugging:

https://github.com/meowsus/deface-haml5-bug

What's funny is that I'm having the same issue, but just in reverse; the data attribute of the partial being injected is losing its data attribute.

Something's going on for sure.

If you have a minute, take a peek at the repo I set up. Here's a screenshot of the compiled source:

![Screenshot from 2019-06-26 15-17-23](https://user-images.githubusercontent.com/1037252/60219201-79bb2d80-9826-11e9-8789-69973d99e199.png)

That `<h1>My Partial!</h1>` should have a `data-foo=''` attribute on it.

I really hope this helps!
