### ISSUE TITLE
Namespacing Config Fails Out of the Box

### ISSUE THREAD

**Issue by brchristian** [spree/deface#210]
I created a brand new Rails (6.0.3.3) app and added Deface to the Gemfile.

Then, following the README, I went into config/application.rb and added the following:

```ruby
config.deface.namespaced = true
```

When I try to run my Rails app, it crashes instantly, with:

```
ruby/2.6.6/gems/railties-6.0.3.3/lib/rails/railtie/configuration.rb:96:in `method_missing’:
undefined method `deface' for #<Rails::Application::Configuration:0x00007ffae8262448> (NoMethodError)
        from fooapp/config/application.rb:19:in `<class:Application>'                                               
	from fooapp/config/application.rb:10:in `<module:Fooapp>'
	from fooapp/config/application.rb:9:in `<top (required)>'
	from ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /ruby/2.6.6/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /ruby/2.6.6/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```

What am I doing wrong?

**Comment by pelargir** [comment]
Same problem.
